### ISSUE TITLE
How can I check if an update is required/available?

### ISSUE THREAD

**Issue by sleewok** [MarsadMaqsood/updater#1]
I am running the update check onInit and I would like to prevent other code from running if an update is available. How can I do this? I don't see where anything is returned that tells me if an update is available.

Thanks!

**Comment by sleewok** [comment]
I modified the updater.dart by adding a bool that is returned by the check() function. This lets me check if an update is available. Can you add this modification to your code, or do you want me to submit a pull request?

`bool updateAvailable = false;

  ///Function to check for update
  check() async {
    if (this.controller != null)
      this.controller!.setValue(UpdateStatus.Checking);

    var response = await http.get(Uri.parse(url));

    var data = jsonDecode(response.body);

    String contentTxt = data['contentText'];
    int versionCodeNew = data['versionCode'];
    String downloadUrl = data['url'];
    int minSupportVersion = data['minSupport'];

    if (callBack != null)
      callBack!(data['versionName'], versionCodeNew, contentTxt,
          minSupportVersion, downloadUrl);

    if (contentText == '') {
      contentText = contentTxt;
    }

    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    int buildNumber = int.parse(packageInfo.buildNumber);

    if (minSupportVersion >= buildNumber) {
      allowSkip = false;
    }

    if (buildNumber < versionCodeNew && downloadUrl.contains('http')) {
      if (controller != null) controller!.setValue(UpdateStatus.Checking);
      _downloadUrl = downloadUrl;
      showDialog(
          context: context,
          barrierDismissible: this.allowSkip,
          builder: (_) {
            return _buildDialog;
          });
      return true;
    }
    return false;
  }
`

**Comment by MarsadMaqsood** [comment]
Please submit a pull request
